FROM {{ namespace }}/openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

COPY sources.list.debian /etc/apt/sources.list.d/ceph.list
RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 460F3994
RUN apt-get update \
    && apt-get install -y --no-install-recommends ceph-common python-ceph python-rados \
    && apt-get clean

{{ copy_sources("openstack/glance", "/glance") }}

RUN useradd --user-group glance \
    && /var/lib/microservices/venv/bin/pip --no-cache-dir install --upgrade -c /glance/requirements.txt /glance \
    && mkdir -p /var/lib/glance /etc/glance \
    && chown -R glance: /etc/glance /var/lib/glance \
    && cp -r /glance/etc/* /etc/glance
