FROM {{ namespace }}/openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{{ copy_sources("openstack/glance", "/glance") }}

RUN useradd --user-group glance \
    && /var/lib/microservices/venv/bin/pip --no-cache-dir install --upgrade -c /glance/requirements.txt /glance \
    && mkdir -p /var/lib/glance /etc/glance \
    && chown -R glance: /var/lib/glance \
    && cp -r /glance/etc/* /etc/glance
