FROM {{ namespace }}/glance-base:{{ tag }}
MAINTAINER {{ maintainer }}

COPY glance-service-registry.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/glance-service-registry.sh

#mysql-client only for provisioning need to be removed later
RUN apt-get install -y --no-install-recommends \
        mysql-client \
    && apt-get clean
